site_name: Hascal Documentation
site_url: https://hascal.github.io
nav:
    - Home Page : 'https://hascal.github.io'
    - Hascal Documentation: index.md
    - Standard Library: stdlib.md
    - Interfacing to C\C++: interfacing.md
    - Library Mangaer: libmanager.md

theme:
  name: readthedocs
  logo: assets/logo.png
  favicon: assets/logo.png

plugins:
  - search
next_previous: true
edit_uri: edit/main/docs/
repo_url: https://github.com/hascal/hascal/
copyright: Copyright &copy; 2019 - 2022 Hascal Foundation